name: "Redis Container Action"
description: "Starts and stops a Redis container"

outputs:
  container_id:
    description: "The docker container id"

runs:
  using: "composite"
  steps:
    - name: Check Docker installation
      id: check_docker
      run: |
        if ! command -v docker &> /dev/null
        then
          echo "Docker could not be found"
          echo "::set-output name=ERROR_MESSAGE::Docker is not installed on this runner"
          exit 1
        fi
      shell: bash

    - name: Start Redis Container
      id: start_container
      run: |
        CONTAINER_ID=$(docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest)
        if [[ -z "$CONTAINER_ID" ]]; then
          echo "Failed to start Redis container"
          exit 1
        else
          echo "::set-output name=container_id::$CONTAINER_ID"
        fi
        echo "Redis container started with ID $CONTAINER_ID"
      shell: bash

    - name: Cleanup
      uses: webiny/action-post-run@3.1.0
      id: post-run-command
      if: ${{ steps.start_container.outputs.container_id }}
      with:
        run: |
          docker stop ${{ steps.start_container.outputs.container_id }}
